version: '3'

networks:
  symfony-app:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-symfony-app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony-app

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: php-symfony-app
    volumes:
      - ./app:/var/www/app
    ports:
      - "9000:9000"
    networks:
      - symfony-app